name: chikitsa
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.2
  cached_network_image: ^2.0.0
  image_picker: ^0.6.1+4
  flutter_switch: ^0.0.2
  drawerbehavior: ^1.0.0
  keyboard_visibility: ^0.5.6
  shared_preferences:
  url_launcher:
  youtube_player_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  cached_network_image: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fontstyle/Montserrat-Regular.ttf
        - asset: assets/fontstyle/Montserrat-Bold.ttf
        - asset: assets/fontstyle/Montserrat-Medium.ttf
        - asset: assets/fontstyle/Montserrat-Black.ttf
        - asset: assets/fontstyle/Lato-Bold.ttf
        - asset: assets/fontstyle/Lato-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fontstyle/Lato-Bold.ttf
        - asset: assets/fontstyle/Lato-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/doctor.png
    - assets/images/logo.png
    - assets/images/patient.png
    - assets/images/bg_img.png
    - assets/images/address.png
    - assets/images/age.png
    - assets/images/email.png
    - assets/images/mobile.png
    - assets/images/password.png
    - assets/images/user.png
    - assets/images/back.png
    - assets/images/bg_main.png
    - assets/images/appointment.png
    - assets/images/changedoctor.png
    - assets/images/covid.png
    - assets/images/logout.png
    - assets/images/nearbyhospital.png
    - assets/images/notes.png
    - assets/images/notifications.png
    - assets/images/dummy.png
    - assets/images/menu.png
    - assets/images/addmedicine.png
    - assets/images/allmedication.png
    - assets/images/missedmedicine.png
    - assets/images/phone.png
    - assets/images/checked.png
    - assets/images/pen.png
    - assets/images/date.png
    - assets/images/time.png
    - assets/images/reject.png
    - assets/images/send.png
    - assets/images/all_patient.png
    - assets/images/doctor_appointment.png
    - assets/images/doctor_profile.png
    - assets/images/doctors.png
    - assets/images/dr_menu.png
    - assets/images/hosp.png
    - assets/images/special.png
    - assets/images/refresh.png
    - assets/images/divider.png
    - assets/images/notify.png
    - assets/images/phill.png
    - assets/images/cross.png
    - assets/images/down.png
    - assets/images/patient_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
